/**
 * GENERATED FILE - DO NOT EDIT
 * This file is automatically generated by the generate-trpc-client script.
 * To update this file, run: npm run generate-hooks
 */

import { trpc } from './trpc';
import { RouterInputs, RouterOutputs } from '../server/src/types/trpc-types';

/**
 * Type-safe hooks for TRPC procedures
 */

// user hooks
export const useUser = {
  // Add strongly typed hooks here
};

// dashboard hooks
export const useDashboard = {
  // Add strongly typed hooks here
};

// value hooks
export const useValue = {
  // Add strongly typed hooks here
};

// principle hooks
export const usePrinciple = {
  // Add strongly typed hooks here
};

// goal hooks
export const useGoal = {
  // Add strongly typed hooks here
};

// task hooks
export const useTask = {
  // Add strongly typed hooks here
};

// habit hooks
export const useHabit = {
  // Add strongly typed hooks here
};

// state hooks
export const useState = {
  // Add strongly typed hooks here
};

// rewards hooks
export const useRewards = {
  // Add strongly typed hooks here
};

// reminder hooks
export const useReminder = {
  // Add strongly typed hooks here
};

// goalProgressNote hooks
export const useGoalProgressNote = {
  // Add strongly typed hooks here
};


// Example type usage
type GreetingOutput = RouterOutputs['greeting']['hello'];
